**Блок по SQL**

Задача: Написать запрос, который будет считать Conversion Rate (CR%) из просмотра (view) в покупку (purchase).

Данные: Таблица "events" (80 строк, 3 столбца). Данные содержать сведения о ID пользователя, его действиях (2 варианта: view - просмотр товара, purchase - покупка) и дата+время этого события.

In [ ]:
import sqlite3 # Подключаем библиотеку SQLlite
import pandas as pd

In [ ]:
conn = sqlite3.connect('events.db')
cursor = conn.cursor()

In [ ]:
cursor.execute("""
DROP TABLE IF EXISTS events;
""")

cursor.execute("""
CREATE TABLE events (
    user_id INTEGER,
    action TEXT,
    event_timestamp TEXT
)
""")

In [ ]:
cursor.executescript("""
INSERT INTO events (user_id, action, event_timestamp) VALUES
(1024, 'purchase', '2024-01-07 12:15:00'),
(1011, 'purchase', '2024-01-04 09:10:01'),
(1033, 'view', '2024-01-10 10:02:00'),
(1005, 'view', '2024-01-02 09:00:00'),
(1043, 'purchase', '2024-01-12 12:45:00'),
(1015, 'purchase', '2024-01-05 11:15:00'),
(1001, 'purchase', '2024-01-01 00:05:00'),
(1029, 'view', '2024-01-09 10:00:00'),
(1038, 'purchase', '2024-01-11 11:15:00'),
(1004, 'purchase', '2024-01-01 12:00:00'),
(1047, 'purchase', '2024-01-13 12:30:00'),
(1022, 'view', '2024-01-07 10:00:00'),
(1008, 'purchase', '2024-01-03 10:20:00'),
(1030, 'purchase', '2024-01-09 11:00:00'),
(1019, 'view', '2024-01-06 10:00:00'),
(1041, 'view', '2024-01-12 10:00:00'),
(1011, 'view', '2024-01-04 09:00:00'),
(1034, 'view', '2024-01-10 11:00:00'),
(1002, 'view', '2024-01-01 10:00:00'),
(1026, 'purchase', '2024-01-08 11:45:00'),
(1050, 'purchase', '2024-01-14 11:00:00'),
(1013, 'purchase', '2024-01-04 11:30:00'),
(1036, 'purchase', '2024-01-10 13:30:00'),
(1005, 'purchase', '2024-01-02 09:30:00'),
(1024, 'view', '2024-01-07 12:00:00'),
(1038, 'view', '2024-01-11 11:00:00'),
(1017, 'view', '2024-01-05 13:00:00'),
(1045, 'purchase', '2024-01-13 10:15:00'),
(1007, 'view', '2024-01-02 15:00:00'),
(1033, 'view', '2024-01-10 10:00:00'),
(1018, 'purchase', '2024-01-06 09:00:00'),
(1022, 'purchase', '2024-01-07 10:30:00'),
(1049, 'purchase', '2024-01-14 10:45:00'),
(1001, 'view', '2023-12-31 23:55:00'),
(1011, 'purchase', '2024-01-04 09:10:00'),
(1032, 'purchase', '2024-01-09 13:15:00'),
(1002, 'view', '2024-01-01 10:05:00'),
(1040, 'purchase', '2024-01-11 13:00:00'),
(1026, 'view', '2024-01-08 11:00:00'),
(1015, 'view', '2024-01-05 11:00:00'),
(1005, 'purchase', '2024-01-02 09:30:00'),
(1029, 'purchase', '2024-01-09 10:30:00'),
(1033, 'view', '2024-01-10 10:01:00'),
(1043, 'view', '2024-01-12 12:00:00'),
(1017, 'purchase', '2024-01-05 13:45:00'),
(1034, 'purchase', '2024-01-10 11:45:00'),
(1008, 'view', '2024-01-03 10:00:00'),
(1024, 'purchase', '2024-01-07 12:15:00'),
(1041, 'purchase', '2024-01-12 10:30:00'),
(1010, 'purchase', '2024-01-04 08:00:00'),
(1038, 'purchase', '2024-01-11 11:15:00'),
(1013, 'view', '2024-01-04 11:00:00'),
(1047, 'view', '2024-01-13 12:00:00'),
(1002, 'purchase', '2024-01-01 10:15:00'),
(1019, 'purchase', '2024-01-06 10:05:00'),
(1036, 'view', '2024-01-10 13:00:00'),
(1045, 'view', '2024-01-13 10:00:00'),
(1032, 'view', '2024-01-09 13:00:00'),
(1007, 'view', '2024-01-02 15:05:00'),
(1049, 'view', '2024-01-14 10:00:00'),
(1003, 'view', '2024-01-01 11:00:00'),
(1006, 'view', '2024-01-02 14:00:00'),
(1009, 'view', '2024-01-03 11:00:00'),
(1012, 'view', '2024-01-04 10:00:00'),
(1014, 'view', '2024-01-05 10:00:00'),
(1016, 'view', '2024-01-05 12:00:00'),
(1020, 'view', '2024-01-06 11:00:00'),
(1021, 'view', '2024-01-06 12:00:00'),
(1023, 'view', '2024-01-07 11:00:00'),
(1025, 'view', '2024-01-08 10:00:00'),
(1027, 'view', '2024-01-08 12:00:00'),
(1028, 'view', '2024-01-08 13:00:00'),
(1031, 'view', '2024-01-09 12:00:00'),
(1035, 'view', '2024-01-10 12:00:00'),
(1037, 'view', '2024-01-11 10:00:00'),
(1039, 'view', '2024-01-11 12:00:00'),
(1042, 'view', '2024-01-12 11:00:00'),
(1044, 'view', '2024-01-12 13:00:00'),
(1046, 'view', '2024-01-13 11:00:00'),
(1048, 'view', '2024-01-13 13:00:00');
""")

conn.commit()

In [ ]:
df = pd.read_sql_query("""
SELECT COUNT(DISTINCT CASE WHEN action='view' THEN user_id END) as view_users,
       COUNT(DISTINCT CASE WHEN action='purchase' THEN user_id END) as purchase_users,
       ROUND(COUNT(DISTINCT CASE WHEN action='purchase' THEN user_id END)*1.0/COUNT(DISTINCT CASE WHEN action='view' THEN user_id END), 2) as CR
FROM events
""", conn)

df

   view_users  purchase_users    CR
0          44              28  0.64

Conversion Rate (CR%) = 0.64 (64%)

Получившееся CR великовато, наводит на более глубокий расчет.

In [ ]:
df_2 = pd.read_sql_query("""
SELECT
    COUNT(DISTINCT v.user_id) AS converted_users,  -- Пользователи из преобразованной таблицы, которые после просмотра совершили покупку
    (SELECT COUNT(DISTINCT user_id)
     FROM events
     WHERE action='view') AS view_users, -- Все пользователи просматривающие товары
    ROUND(
      COUNT(DISTINCT v.user_id) * 1.0 / (SELECT COUNT(DISTINCT user_id)
                                             FROM events
                                             WHERE action='view'),
    2) AS CR
FROM events v                       -- Пользователи у которых v.action = 'view'
JOIN events p                       -- Только совпадение с пользователями которые в итоге совершили покупку p.action = 'purchase' и время покупки больше времени просмотра
  ON v.user_id = p.user_id
WHERE v.action = 'view'
  AND p.action = 'purchase'
  AND p.event_timestamp > v.event_timestamp
  """, conn)

df_2

   converted_users  view_users   CR
0               22          44  0.5

Conversion Rate (CR%) = 0,5 (50%)

Это конверсия выблядит лучше, более реалистичная, хоть и тоже великовата.

**Блок по Python**

Задача: Напишите функцию, которая принимает список транзакций из переменной transactions и возвращает сумму выручки.

In [ ]:
transactions = [
    {"id": 1, "price": "100$"}, {"id": 2, "price": "85€"}, {"id": 3, "price": "150$"},
    {"id": 4, "price": "-50$"}, {"id": 5, "price": "12.5$"}, {"id": 6, "price": " 200$ "},
    {"id": 7, "price": None}, {"id": 8, "price": "45€"}, {"id": 9, "price": "1,000.00$"},
    {"id": 10, "price": "invalid"}, {"id": 11, "price": "99$"}, {"id": 12, "price": "15€"},
    {"id": 13, "price": "100.50$"}, {"id": 14, "price": "-15€"}, {"id": 15, "price": "0$"},
    {"id": 16, "price": "500$"}, {"id": 17, "price": "NaN"}, {"id": 18, "price": "120€"},
    {"id": 19, "price": " 30.5€ "}, {"id": 20, "price": "2,500.50$"}, {"id": 21, "price": "50$"},
    {"id": 22, "price": "75€"}, {"id": 23, "price": None}, {"id": 24, "price": "10$"},
    {"id": 25, "price": "error_val"}, {"id": 26, "price": "80$"}, {"id": 27, "price": "25€"},
    {"id": 28, "price": "100,00€"}, {"id": 29, "price": "-100$"}, {"id": 30, "price": "150$"},
    {"id": 31, "price": "200€"}, {"id": 32, "price": " 5$ "}, {"id": 33, "price": "99.99$"},
    {"id": 34, "price": None}, {"id": 35, "price": "40€"}, {"id": 36, "price": "300$"},
    {"id": 37, "price": "-20€"}, {"id": 38, "price": "1.500,00€"}, {"id": 39, "price": "50$"},
    {"id": 40, "price": "bad_data"}, {"id": 41, "price": "110$"}, {"id": 42, "price": "60€"},
    {"id": 43, "price": "250$"}, {"id": 44, "price": None}, {"id": 45, "price": "15.99$"},
    {"id": 46, "price": " 100€ "}, {"id": 47, "price": "75$"}, {"id": 48, "price": "-5$"},
    {"id": 49, "price": "1200$"}, {"id": 50, "price": "0€"}, {"id": 51, "price": "85$"},
    {"id": 52, "price": "30€"}, {"id": 53, "price": "199.99$"}, {"id": 54, "price": None},
    {"id": 55, "price": "test"}, {"id": 56, "price": "50€"}, {"id": 57, "price": "10,000$"},
    {"id": 58, "price": "-30$"}, {"id": 59, "price": "45$"}, {"id": 60, "price": "90€"},
    {"id": 61, "price": "150$"}, {"id": 62, "price": " 20$ "}, {"id": 63, "price": None},
    {"id": 64, "price": "60$"}, {"id": 65, "price": "broken"}, {"id": 66, "price": "110€"},
    {"id": 67, "price": "5,000.00$"}, {"id": 68, "price": "-15$"}, {"id": 69, "price": "80€"},
    {"id": 70, "price": "200$"}, {"id": 71, "price": "35$"}, {"id": 72, "price": " 150€ "},
    {"id": 73, "price": "25$"}, {"id": 74, "price": None}, {"id": 75, "price": "99.50$"},
    {"id": 76, "price": "0$"}, {"id": 77, "price": "null"}, {"id": 78, "price": "130$"},
    {"id": 79, "price": "-50€"}, {"id": 80, "price": "70$"}, {"id": 81, "price": "40€"},
    {"id": 82, "price": "180$"}, {"id": 83, "price": " 10$ "}, {"id": 84, "price": None},
    {"id": 85, "price": "300€"}, {"id": 86, "price": "1,200.50$"}, {"id": 87, "price": "55$"},
    {"id": 88, "price": "-25$"}, {"id": 89, "price": "N/A"}, {"id": 90, "price": "90$"},
    {"id": 91, "price": "20€"}, {"id": 92, "price": "140$"}, {"id": 93, "price": " 50$ "},
    {"id": 94, "price": None}, {"id": 95, "price": "75.25$"}, {"id": 96, "price": "100€"},
    {"id": 97, "price": "0.99$"}, {"id": 98, "price": "-10€"}, {"id": 99, "price": "250$"},
    {"id": 100, "price": "15€"}
]

In [ ]:
def correct_price(price):
  if price is None:
    return 0

  if '$' in price:
    currency = 'USD'
  elif '€' in price:
    currency = 'EUR'

  price = price.replace('$', '').replace('€', '')

  price = str(price).strip()

  if ',' in price and '.' in price:
    if price.find(',') < price.find('.'):
      price = price.replace(',', '')
    else:
      price = price.replace('.', '').replace(',', '.')

  elif ',' in price:
    price = price.replace(',', '.')

  if price in ['invalid', 'NaN', 'error_val', 'bad_data', 'test', 'broken', 'null', 'N/A']:
    return 0

  corr_price = float(price)

  if currency == 'EUR':
    corr_price = 1.1 * corr_price

  return corr_price


def revenue(transactions):
  total_revenue = 0
  for trans in transactions:
    total_revenue += correct_price(trans['price'])
  return total_revenue

print(f'Сумма выручки по транзакциям равна {round(revenue(transactions),2)} USD')

Сумма выручки по транзакциям равна 18628.76 USD